version: "3"

services: 
    web:
        container_name: exampleapp
        restart: always
        build: .
        ports: 
            - "5000:3000"
        links: 
            - base
    base:
        container_name: basedatos
        image: postgres
        restart: always
        ports: 
            - "5444:5432"
        environment: 
            POSTGRES_PASSWORD: root
            POSTGRES_DB: metodos